[package]
name = "postgres_rust"
version = "0.1.0"
authors = ["hunterlester <guilfordhunter@gmail.com>"]

[dependencies]
nickel = "0.9.0"
postgres = { version = "0.12", features = ["with-chrono"]}
chrono = "0.2"
rustc-serialize = "0.3"
